includes:
- configs/md22/Ac-Ala3/gemnet-dT-small.yml

trainer: src.distill_trainer.DistillTrainer

dataset:
  train:
    teacher_checkpoint_path: checkpoints/ac_Ala3_5k_gemnet_t/best_checkpoint.pt
    teacher_labels_folder: labels/ac_Ala3_5k_gemnet_t
    label_force_batch_size: 30
    label_jac_batch_size: 1
    vectorize_teach_jacs: True

loss_functions:
  - energy:
      fn: mae
      coefficient: .25
  - forces:
      fn: l2mae
      coefficient: 250
  - teacher_forces:
      fn: l2mae
      coefficient: 0
  - force_jacs:
      fn: l2mae
      coefficient: 1000
      reduction: mean_all

optim:
  batch_size: 1
  eval_batch_size: 32
  force_jac_sample_size: 30
  print_memory_usage: False
  vectorize_jacs: True
