includes:
- configs/SPICE/iodine/gemnet-dT-small.yml

trainer: src.distill_trainer.DistillTrainer

dataset:
  train:
    teacher_labels_folder: data/labels/SPICE_labels/mace_off_large_SpiceIodine

loss_functions:
  - energy:
      fn: per_atom_mae
      coefficient: 5
  - forces:
      fn: l2mae
      coefficient: 100
  - teacher_forces:
      fn: l2mae
      coefficient: 0
  - force_jacs:
      fn: l2mae
      coefficient: 400

optim:
  force_jac_sample_size: 4
  print_memory_usage: False
  vectorize_jacs: True
  energy_distill_coeff: 5
