includes:
- configs/SPICE/iodine/gemnet-dT-small.yml

trainer: src.distill_trainer.DistillTrainer

dataset:
  train:
    label_force_batch_size: 32
    label_jac_batch_size: 4
    vectorize_teach_jacs: True


loss_functions:
  - energy:
      fn: mae
      coefficient: 0
  - forces:
      fn: l2mae
      coefficient: 0
  - teacher_forces:
      fn: l2mae
      coefficient: 100
  - force_jacs:
      fn: l2mae
      coefficient: 0


evaluation_metrics:
  metrics:
    energy:
      - mae
    forces:
      - mae
      - cosine_similarity
      - magnitude_error
    misc:
      - energy_forces_within_threshold
  primary_metric: forces_mae
  

optim:
  batch_size: 32
  eval_batch_size: 32
  force_jac_sample_size: 10
  print_memory_usage: False
  vectorize_jacs: True
