includes:
- configs/MPTraj/Yttrium/gemnet-dT-small.yml

trainer: src.distill_trainer.DistillTrainer

dataset:
  train:
    teacher_labels_folder: data/labels/MPtraj_labels/mace_mp_all_splits_Yttrium

loss_functions:
  - energy:
      fn: per_atom_mae
      coefficient: 5
  - forces:
      fn: l2mae
      coefficient: 100
  - teacher_forces:
      fn: l2mae
      coefficient: 0
  - force_jacs:
      fn: l2mae
      coefficient: 200

optim:
  force_jac_sample_size: 4
  print_memory_usage: False
  vectorize_jacs: True
  energy_distill_coeff: 5