includes:
- configs/SPICE/solvated_amino_acids/gemnet-dT-small.yml

trainer: src.distill_trainer.DistillTrainer

dataset:
  train:
    teacher_labels_folder: labels/SPICE_labels/mace_off_large_SpiceAminos
    label_force_batch_size: 32
    label_jac_batch_size: 4
    vectorize_teach_jacs: True

loss_functions:
  - energy:
      fn: mae
      coefficient: 0
  - forces:
      fn: l2mae
      coefficient: 100
  - teacher_forces:
      fn: l2mae
      coefficient: 0
  - force_jacs:
      fn: l2mae
      coefficient: 400
      reduction: mean_all

optim:
  batch_size: 4
  eval_batch_size: 32
  force_jac_sample_size: 10
  print_memory_usage: False
  vectorize_jacs: True
