includes:
- configs/MPTraj/Bandgap_greater_5/gemnet-dT-small.yml

trainer: src.distill_trainer.DistillTrainer

dataset:
  train:
    teacher_labels_folder: data/labels/MPtraj_labels/mace_mp_all_splits_Bandgap_greater_5

loss_functions:
  - energy:
      fn: mae
      coefficient: 1
  - forces:
      fn: l2mae
      coefficient: 100
  - teacher_forces:
      fn: l2mae
      coefficient: 0
  - force_jacs:
      fn: l2mae
      coefficient: 200

optim:
  force_jac_sample_size: 1
  print_memory_usage: False
  vectorize_jacs: True
  energy_distill_coeff: 2