includes:
- configs/MPTraj/Bandgap_greater_5/painn/painn-small.yml

trainer: src.distill_trainer.DistillTrainer

dataset:
  train:
    teacher_labels_folder: /data/shared/ishan_stuff/mptraj_seperated_all_splits/mace_mp_all_splits_Bandgap_greater_5

model:
  use_teacher_atom_embeddings: False

outputs:
  final_node_features:
    irrep_dim: 1
    level: atom
    train_on_free_atoms: True
    eval_on_free_atoms: True
    
loss_functions:
  - energy:
      fn: mae
      coefficient: 0
  - forces:
      fn: l2mae
      coefficient: 100
  - teacher_forces:
      fn: l2mae
      coefficient: 0
  - final_node_features:
      fn: mse
      coefficient: 1000
  - force_jacs:
      fn: l2mae
      coefficient: 100
      reduction: mean_all

evaluation_metrics:
  metrics:
    energy:
      - mae
    forces:
      - mae
      - cosine_similarity
      - magnitude_error
    final_node_features:
      - mse
    misc:
      - energy_forces_within_threshold
  primary_metric: forces_mae

optim:
  batch_size: 32
  eval_batch_size: 32
  force_jac_sample_size: 1
  print_memory_usage: False
  vectorize_jacs: True
