includes:
- configs/md22/AT-AT/painn/painn-small.yml

trainer: src.distill_trainer.DistillTrainer

dataset:
  train:
    teacher_checkpoint_path: teacher_checkpoints/AT-AT_all-gemT-normOFF-1094epochs/best_checkpoint.pt
    teacher_labels_folder: labels/AT-AT-gemT-1094epochs
    label_force_batch_size: 32
    label_jac_batch_size: 32
    vectorize_teach_jacs: False

loss_functions:
  - energy:
      fn: mae
      coefficient: 0
  - forces:
      fn: l2mae
      coefficient: 100
  - teacher_forces:
      fn: l2mae
      coefficient: 0
  - force_jacs:
      fn: l2mae
      coefficient: 400
      reduction: mean_all

optim:
  batch_size: 16
  eval_batch_size: 32
  force_jac_sample_size: 4
  print_memory_usage: False
  vectorize_jacs: True
